services:
  nomad:
    container_name: nomad
    image: hashicorp/nomad:1.6.10
    command: nomad agent -config /etc/nomad.d
    entrypoint: ""
    ports:
      - 4646:4646
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ${PWD}/nomadconfig.hcl:/etc/nomad.d/config.hcl:ro
